#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Spring cloud를 통해 변경이 가능한 요소들을 정의한다.
#----------------------------------------------------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: zuul-server-local
