server:
  port: ${PORT:7071}
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}:${EUREKA_SERVER_PORT:7070}/eureka/
  server:
    enable-self-preservation: true
---
spring:
  profiles: stage-eureka1
eureka:
  instance:
    hostname: stage-eureka1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}:${EUREKA_SERVER_PORT:7070}/eureka/
  server:
    enable-self-preservation: true
---
spring:
  profiles: stage-eureka2
eureka:
  instance:
    hostname: stage-eureka2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}:${EUREKA_SERVER_PORT:7070}/eureka/
  server:
    enable-self-preservation: true
---
spring:
  profiles: docker
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}:${EUREKA_SERVER_PORT:7070}/eureka/
  server:
    enable-self-preservation: true